(define (problem goal-green-red-blue)
    (:domain manito)

    (:objects
        greenb blueb redb whiteb
        garra
        xygarra xygreen xyblue xyred xywhite
        zgreen zgarra zblue zred zwhite
    )

    (:init
        (en greenb xygreen)
        (pisob greenb zgreen)
        (libre greenb)
        (en blueb xyblue)
        (pisob blueb zblue)
        (libre blueb)
        (en redb xyred)
        (pisob redb zred)
        (libre redb)
        (en whiteb xywhite)
        (pisob whiteb zwhite)
        (libre whiteb)
        (pos garra xygarra)
        (pisog garra zgarra)
        (dismover garra)
        (desocupado garra)
        (camino xygreen xygarra)
        (camino xygarra xygreen)
        (camino xygarra xyblue)
        (camino xyblue xygarra)
        (camino xygarra xyred)
        (camino xyred xygarra)
        (camino xygarra xywhite)
        (camino xywhite xygarra)
        (camino xygreen xyblue)
        (camino xyblue xygreen)
        (camino xygreen xyred)
        (camino xyred xygreen)
        (camino xygreen xywhite)
        (camino xywhite xygreen)
        (camino xyblue xyred)
        (camino xyred xyblue)
        (camino xyblue xywhite)
        (camino xywhite xyblue)
        (camino xyred xywhite)
        (camino xywhite xyred)
        (alt zgarra zgreen)
        (alt zgreen zgarra)
        (alt zblue zgarra)
        (alt zgarra zblue)
        (alt zred zgarra)
        (alt zgarra zred)
        (alt zwhite zgarra)
        (alt zgarra zwhite)
    )

    (:goal 
        (and 
            (torre blueb greenb)
            (torre whiteb redb)
        )
    )
)