# configs/scenarios/scenario_8.yml
viewer:
  camera_pos: [1.5, 1.5, 1.5]
  camera_lookat: [0.0, 0.0, 0.40]

environment:
  plane: true
  gravity: [0.0, 0.0, -9.81]

robots:
  - name: "Manito"
    urdf_path: "assets/robots/manito/manito.urdf"
    position: [0.0, 0.0, -0.04]
    fixed: true
    is_main: true

objects:
  - type: "box"
    size: [0.04, 0.04, 0.04]
    pos: [0.0, 0.20, 0.0]
    surface: "rough"
    color: [0.1, 0.8, 0.3]
    name: "green"

  - type: "box"
    size: [0.04, 0.04, 0.04]
    pos: [0.0, 0.20, 0.04]
    surface: "rough"
    color: [0.1, 0.3, 0.8]
    name: "blue"

  - type: "box"
    size: [0.04, 0.04, 0.04]
    pos: [0.3, 0.0, 0.0]
    surface: "rough"
    color: [0.8, 0.8, 0.8]
    name: "white"

stream_camera:
  pos: [1.0, 1.0, 1.5]
  lookat: [0.0, 0.0, 0.40]
  res: [640, 480]

objectives:
  - id: "Desapilar3"
    description: "Deja el bloque verde de la torre sobre el bloque blanco."